### ISSUE TITLE
送礼物功能无法使用

### ISSUE THREAD

**Issue by Keymorek** [qianjiachun/douyuEx#1]
你好，
本来没发连送的礼物还是没法使用插件连送，比如飞机超火礼物。
之前自己测过好像是服务器自动会拒绝这样的礼物。
可能只能模拟单点方式来连送礼物。

送礼代码id示例那边不完整，可以通过GET http://open.douyucdn.cn/api/RoomApi/room/房间号 获取不同房间的礼物

**Comment by qianjiachun** [comment]
好像确实是这样。测试下来飞机火箭这些无法复数发送的礼物都会error。但是办卡超过9999似乎不会error 不知是否可行。。反正是个测试功能，放着吧哈哈

**Comment by Keymorek** [comment]
我去……… 那9999办卡也没法测试了

With best regards ,
Lyurun Fang
2020年1月31日 -0500 22:49 qianjiachun <notifications@github.com>，写道：

**Comment by Keymorek** [comment]
我去……
那也没法测试了

**Comment by qianjiachun** [comment]
已修复
