### ISSUE TITLE
找不到简洁模式入口

### ISSUE THREAD

**Issue by AirManH** [qianjiachun/douyuEx#10]
<img width="531" alt="Snipaste_2020-06-17_15-58-42" src="https://user-images.githubusercontent.com/30146150/84871992-d658cd80-b0b3-11ea-8326-5d1f2871a14b.png">

在图片中，我已经把鼠标移到视频区域，但是没有找到“简”字

**Comment by qianjiachun** [comment]
重新刷新一下试试？这个简字出现的会比较晚，是所有其他代码加载完毕后最后再出现的

**Comment by AirManH** [comment]
我并不是很了解JS，但是我进行了一些基本的调试。

测试环境是这样的

- `Tampermonkey v4.10`
- `@version      2020.06.15.02`
- `Google Chrome 83.0.4103.106 64bit`
- Surface Go

我在4183行`initPkg_Refresh_Video`函数里加入了`console.log`用来调试：

``` javascript
function initPkg_Refresh_Video() {
    setTimeout(() => {
        console.log("隐藏礼物框函数：initPkg_Refresh_Video， len:" + document.getElementsByClassName("right-e7ea5d").length);
        if (document.getElementsByClassName("right-e7ea5d").length > 0) {
            initPkg_Refresh_Video_Dom();
            initPkg_Refresh_Video_Func();
            initPkg_Refresh_Video_Set();
        }
    }, 1500);
}
```

控制台有时显示`len:0`，有时为`len:1`。注意到我的Surface Go性能不佳网页加载慢，我猜测是`setTimeout`函数里代表延时的`1500`过短导致的。我觉得`setTimeout`函数不合适，需要一个更好的实现方法。

**Comment by qianjiachun** [comment]
感谢反馈。已记录，后续版本会进行持续优化。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Air"<notifications@github.com&gt;; 
发送时间: 2020年6月18日(星期四) 中午11:09
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;; 
抄送: "小淳"<189964430@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [qianjiachun/douyuEx] 找不到简洁模式入口 (#10)





 
我并不是很了解JS，但是我进行了一些基本的调试。
 
测试环境是这样的
  
Tampermonkey v4.10
 
@version      2020.06.15.02
 
Google Chrome 83.0.4103.106 64bit
 
Surface Go
  
我在4183行initPkg_Refresh_Video函数里加入了console.log用来调试：
 function initPkg_Refresh_Video() {     setTimeout(() =&gt; {         console.log("隐藏礼物框函数：initPkg_Refresh_Video， len:" + document.getElementsByClassName("right-e7ea5d").length);         if (document.getElementsByClassName("right-e7ea5d").length &gt; 0) {             initPkg_Refresh_Video_Dom();             initPkg_Refresh_Video_Func();             initPkg_Refresh_Video_Set();         }     }, 1500); }
 
控制台有时显示len:0，有时为len:1。注意到我的Surface Go性能不佳网页加载慢，我猜测是setTimeout函数里代表延时的1500过短导致的。我觉得setTimeout函数不合适，需要一个更好的实现方法。

**Comment by qianjiachun** [comment]
已修复

**Comment by AirManH** [comment]
fixed in https://github.com/qianjiachun/douyuEx/commit/dfb021bb892c63951b1c07cad75531873bfa7b27
