### ISSUE TITLE
撒时候能开发surge、quantumult x的定时任务脚本

### ISSUE THREAD

**Issue by lowking** [qianjiachun/douyuEx#11]
一些签到任务撒的，可以通过surge、quantumult x软件每天自动执行
希望有空能开发下

**Comment by qianjiachun** [comment]
设计初衷是希望用户与网页有一些交互的，而不是全自动。。
所以如果要全自动的话，可以自己定制噢，反正是开源的。。

**Comment by lowking** [comment]
> 设计初衷是希望用户与网页有一些交互的，而不是全自动。。
> 所以如果要全自动的话，可以自己定制噢，反正是开源的。。

好吧，有空试试
