### ISSUE TITLE
希望增加每日定时执行的功能

### ISSUE THREAD

**Issue by Cairl** [qianjiachun/douyuEx#13]
每日定时执行，改进一件续牌方式，适用长时间无人监管的电脑上挂机

**Comment by qianjiachun** [comment]
产品设计初衷是希望用户与浏览器有一定交互的，而不是完全托管。。所以暂时没有这方面的打算。可以自行DIY一下~

**Comment by LakeishaKowalczyk** [comment]
+1
减轻心智负担

**Comment by LakeishaKowalczyk** [comment]
@qianjiachun 
来嘛来嘛，自动续牌子就好了
