### ISSUE TITLE
希望加一个加长关注栏或者过滤录播主播的功能

### ISSUE THREAD

**Issue by Peanutzzz** [qianjiachun/douyuEx#15]
自从斗鱼开了放录播以后关注快捷栏的五个位置根本不够用了，小主播有没有开播只能点进关注页才能看到很麻烦。有可能加长一下比如显示十个位置或者过滤掉放录播的嘛。

**Comment by qianjiachun** [comment]
已更新
“重写了斗鱼的关注列表，现在可以显示10个主播并且能够过滤录播，加上了刷新按钮”
