### ISSUE TITLE
希望在一键清空背包功能中包括抢红包获得的礼物

### ISSUE THREAD

**Issue by Cairl** [qianjiachun/douyuEx#16]
希望在“一键清空背包”的功能中添加抢红包得到的礼物一起送掉的功能
斗鱼在这方面没标清抢红包得到的礼物是在哪个直播间抢到的，礼物一多就记不住了，
如果这个功能很难实现的话，看看能不能简化成标明每个红包礼物是属于哪个直播间的呢？这个就足够了，当然能一起送掉就最好了

**Comment by qianjiachun** [comment]
在红包记录里有相关信息
