### ISSUE TITLE
希望增加记住ddocr密钥的功能

### ISSUE THREAD

**Issue by Cairl** [qianjiachun/douyuEx#17]
每次进入直播间都要手动填真的很麻烦

**Comment by qianjiachun** [comment]
已经有了。填写好密钥后重新勾选一下就是保存了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Cairl&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月26日(星期六) 下午2:43
收件人:&nbsp;&quot;qianjiachun/douyuEx&quot;<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 希望增加记住ddocr密钥的功能 (#17)

**Comment by Cairl** [comment]
原来如此
