### ISSUE TITLE
在mac端运行该脚本，电脑会很卡

### ISSUE THREAD

**Issue by XiaoPi2** [qianjiachun/douyuEx#21]
首先谢谢chun哥的脚本，用了快一年了吧，真的挺有用的。

我的运行环境，macbook pro 16寸， 系统： mac os big sur，浏览器chrome或者safari，edge上也测试过。
好像之前没升级系统前还没有这个问题，最近只要开着douyuEx脚本，电脑没几分钟就会很卡，很掉帧。之前还以为是斗鱼的问题，今天开关脚本测试后才发现是脚本的问题。
希望能得到改善
谢谢啦

**Comment by qianjiachun** [comment]
感谢反馈。听上去像是内存泄露之类的问题，你可以检查一下卡的时候内存占用多少。
斗鱼原生网页本身就存在着越用越卡 内存占用越大的问题。


我自己测试的时候 插件对内存的影响并不是很大，可能还有一些疏忽吧，我后面再检查一下。
一时半会改善不了这个问题。


你可以尝试注释掉源代码中initPkg_LiveTool这个模块，或者多注释掉几个模块，看看会不会改善，以帮助我定位问题所在。

---原始邮件---
发件人: "XiaoPi2"<notifications@github.com&gt;
发送时间: 2020年11月30日(周一) 晚上9:37
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [qianjiachun/douyuEx] 在mac端运行该脚本，电脑会很卡 (#21)




 
首先谢谢chun哥的脚本，用了快一年了吧，真的挺有用的。
 
我的运行环境，macbook pro 16寸， 系统： mac os big sur，浏览器chrome或者safari，edge上也测试过。
 好像之前没升级系统前还没有这个问题，最近只要开着douyuEx脚本，电脑没几分钟就会很卡，很掉帧。之前还以为是斗鱼的问题，今天开关脚本测试后才发现是脚本的问题。
 希望能得到改善
 谢谢啦

**Comment by XiaoPi2** [comment]
> 感谢反馈。听上去像是内存泄露之类的问题，你可以检查一下卡的时候内存占用多少。 斗鱼原生网页本身就存在着越用越卡 内存占用越大的问题。 我自己测试的时候 插件对内存的影响并不是很大，可能还有一些疏忽吧，我后面再检查一下。 一时半会改善不了这个问题。 你可以尝试注释掉源代码中initPkg_LiveTool这个模块，或者多注释掉几个模块，看看会不会改善，以帮助我定位问题所在。
> […](#)

注掉liveTool来运行，确实有所缓解。
感觉根源还是斗鱼的问题
