### ISSUE TITLE
macOS  BigSur下，使用Safari浏览器中的油猴加载该插件。礼物背包被遮挡。

### ISSUE THREAD

**Issue by linxuchuan** [qianjiachun/douyuEx#22]
![image](https://user-images.githubusercontent.com/38499278/101626031-48a0de00-3a57-11eb-8cc8-74836f6fc559.png)
如图。礼物背包被视频盖住了。

**Comment by linxuchuan** [comment]
是最近一次跟新才出现的。之前的版本没问题

**Comment by qianjiachun** [comment]
开了简洁模式。
鼠标移到视频工具条里 点那个简字就行



---原始邮件---
发件人: "linxu_c"<notifications@github.com&gt;
发送时间: 2020年12月9日(周三) 晚上7:48
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [qianjiachun/douyuEx] macOS  BigSur下，使用Safari浏览器中的油猴加载该插件。礼物背包被遮挡。 (#22)




 
是最近一次跟新才出现的。之前的版本没问题

**Comment by linxuchuan** [comment]
> 开了简洁模式。 鼠标移到视频工具条里 点那个简字就行
> […](#)
> ---原始邮件--- 发件人: "linxu_c"<notifications@github.com&gt; 发送时间: 2020年12月9日(周三) 晚上7:48 收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [qianjiachun/douyuEx] macOS BigSur下，使用Safari浏览器中的油猴加载该插件。礼物背包被遮挡。 (#22) 是最近一次跟新才出现的。之前的版本没问题 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

哦哦是的。关掉简洁模式就好了
