### ISSUE TITLE
关于直播间工具，的操作

### ISSUE THREAD

**Issue by soyuzom** [qianjiachun/douyuEx#23]
最近使用使用 直播间工具 发现，添加编辑有点麻烦，而且操作不够简易。
近几个版本都试过关键词回复，添加完，再点击修改时，发现竟然错乱了，回复内容全部一样。
能否修改成文本框编辑方式(就像弹幕工具)，一行一个 关键词+回复，比如：
录播？;是的！@<id>： <txt>
录播？;哇，被你发现！@<id>： <txt>
自动回复;你猜对了！@<id>： <txt>

【进场欢迎】【谢礼物】，都可以这样设置，这样更容易编辑和修改。让重复关键词的可以随机选择。

**Comment by qianjiachun** [comment]
其实是没法修改的，只能删除再重新添加。
我一开始想图方便整个文本框+换行模式的，但是怕用户用不懂。
现在我会重新考虑一下这些功能的设计。


谢谢建议，后续改动留意版本更新



---原始邮件---
发件人: "SoyuZom"<notifications@github.com&gt;
发送时间: 2020年12月22日(周二) 晚上11:56
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [qianjiachun/douyuEx] 关于直播间工具，的操作 (#23)




 
最近使用使用 直播间工具 发现，添加编辑有点麻烦，而且操作不够简易。
 近几个版本都试过关键词回复，添加完，再点击修改时，发现竟然错乱了，回复内容全部一样。
 能否修改成文本框编辑方式(就像弹幕工具)，一行一个 关键词+回复，比如：
 录播？;是的！@： 
 录播？;哇，被你发现！@： 
 自动回复;你猜对了！@： 
 
【进场欢迎】【谢礼物】，都可以这样设置，这样更容易编辑和修改。让重复关键词的可以随机选择。
