### ISSUE TITLE
希望能屏蔽掉长时间挂着直播间不操作提示在不在看，导致直播被暂停

### ISSUE THREAD

**Issue by lowking** [qianjiachun/douyuEx#24]

**Comment by qianjiachun** [comment]
我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月25日(星期五) 晚上8:54
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 希望能屏蔽掉长时间挂着直播间不操作提示在不在看，导致直播被暂停 (#24)
