### ISSUE TITLE
关于每次更新脚本要点击授权支持跨域问题

### ISSUE THREAD

**Issue by popsee** [qianjiachun/douyuEx#25]
淳宝的插件越来越强大了，代码撸到了7K+，Web+移动端全覆盖，奏事牛批！！！
提个小优化，每次更新后或新安装插件都弹出跨域访问的安全提示，能否在油猴脚本头部上加个@connect  域名  比如：
// @connect      jsdelivr.net
// @connect      bojianger.com
来避免总弹出确认按钮，提高友好度！
车队签到可以用，不激活页面（隐藏页面打开）的方式来执行车队签到，再自动签到，感觉效果可能会更好些，如
// @grant        GM_openInTab
用例：GM_openInTab('https://msg.douyu.com/motorcade/',{active: false});//unfocus new tab
最后一个是关于插件的安全声明问题，因为后期看你代码放在自家网址维护并增加了压缩混淆，建议声明里增加一个不窃取用户隐私敏感的数据声明还是有必要的，毕竟互联网经常被GOV被整饬，树大招风嘛，有备无患！
小小建议，仅凭参考！如有冒犯，还请海涵！

**Comment by qianjiachun** [comment]
哈哈感谢提醒，我后面版本会进行相应修改测试



---原始邮件---
发件人: "lvlanxingapp"<notifications@github.com&gt;
发送时间: 2020年12月26日(周六) 下午5:23
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [qianjiachun/douyuEx] 关于每次更新脚本要点击授权支持跨域问题 (#25)




 
淳宝的插件越来越强大了，代码撸到了7K+，Web+移动端全覆盖，奏事牛批！！！
 提个小优化，每次更新后或新安装插件都弹出跨域访问的安全提示，能否在油猴脚本头部上加个@connect  域名  比如：
 // @connect      jsdelivr.net
 // @connect      bojianger.com
 来避免总弹出确认按钮，提高友好度！
 车队签到可以用，不激活页面（隐藏页面打开）的方式来执行车队签到，再自动签到，感觉效果可能会更好些，如
 // @grant        GM_openInTab
 用例：GM_openInTab('https://msg.douyu.com/motorcade/',{active: false});//unfocus new tab
 最后一个是关于插件的安全声明问题，因为后期看你代码放在自家网址维护并增加了压缩混淆，建议声明里增加一个不窃取用户隐私敏感的数据声明还是有必要的，毕竟互联网经常被GOV被整饬，树大招风嘛，有备无患！
 小小建议，仅凭参考！如有冒犯，还请海涵！

**Comment by nvv5** [comment]
> 
> 
> 淳宝的插件越来越强大了，代码撸到了7K+，Web+移动端全覆盖，奏事牛批！！！
> 提个小优化，每次更新后或新安装插件都弹出跨域访问的安全提示，能否在油猴脚本头部上加个@connect 域名 比如：
> // @connect jsdelivr.net
> // @connect bojianger.com
> 来避免总弹出确认按钮，提高友好度！
> 车队签到可以用，不激活页面（隐藏页面打开）的方式来执行车队签到，再自动签到，感觉效果可能会更好些，如
> // @grant GM_openInTab
> 用例：GM_openInTab('[https://msg.douyu.com/motorcade/',{active](https://msg.douyu.com/motorcade/',%7Bactive): false});//unfocus new tab
> 最后一个是关于插件的安全声明问题，因为后期看你代码放在自家网址维护并增加了压缩混淆，建议声明里增加一个不窃取用户隐私敏感的数据声明还是有必要的，毕竟互联网经常被GOV被整饬，树大招风嘛，有备无患！
> 小小建议，仅凭参考！如有冒犯，还请海涵！

你出山了？？好久没联系了，看你最近疯狂更新，在搞什么带项目？
