### ISSUE TITLE
调节弹幕大小的按钮失效了

### ISSUE THREAD

**Issue by xmasrain** [qianjiachun/douyuEx#27]
RT

**Comment by qianjiachun** [comment]
收到反馈，下版本更新



---原始邮件---
发件人: "xmasrain"<notifications@github.com&gt;
发送时间: 2021年1月3日(周日) 晚上11:14
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [qianjiachun/douyuEx] 调节弹幕大小的按钮失效了 (#27)




 
RT
