### ISSUE TITLE
查弹幕功能是不是失效了

### ISSUE THREAD

**Issue by CosmoZzZzZzZ** [qianjiachun/douyuEx#28]
![image](https://user-images.githubusercontent.com/65810385/104733133-36fad680-5779-11eb-974a-02d676e199b9.png)
如图

**Comment by qianjiachun** [comment]
亲测有效。请尝试更新一下脚本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 晚上9:33
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 查弹幕功能是不是失效了 (#28)





 

 如图

**Comment by CosmoZzZzZzZ** [comment]
> 亲测有效。请尝试更新一下脚本
> […](#)

我试了一下，Safari不能用，Chrome可以用。
M1 macOS BigSur V11.1

**Comment by qianjiachun** [comment]
坏了，我对safari的兼容性了解甚少。不太清楚为什么会这样。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月17日(星期天) 中午11:05
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"小淳"<189964430@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 查弹幕功能是不是失效了 (#28)





  
亲测有效。请尝试更新一下脚本
 …
  
我试了一下，Safari不能用，Chrome可以用。
 M1 macOS BigSur V11.1

**Comment by CosmoZzZzZzZ** [comment]
> 坏了，我对safari的兼容性了解甚少。不太清楚为什么会这样。。
> […](#)

好的好的谢谢老大！我再试试！
