### ISSUE TITLE
建议把直播间的PK也屏蔽了

### ISSUE THREAD

**Issue by jklau98** [qianjiachun/douyuEx#29]
看个电影总是弹出来，很烦

**Comment by qianjiachun** [comment]
截个图看看你想要屏蔽哪个框。顺便说一下触发流程。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月9日(星期二) 中午12:16
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 建议把直播间的PK也屏蔽了 (#29)





 
看个电影总是弹出来，很烦

**Comment by jklau98** [comment]
![pic](https://user-images.githubusercontent.com/23568657/107631262-a512ba80-6c9f-11eb-8442-aa5801166913.png)
没有触发流程，只要主播开启PK，就会一直匹配对手
红圈里是在PK开始时的提示，几秒后消失
蓝圈里是PK过程中一直显示的倒计时，可以手动关闭，当匹到新对手时重复这个过程

**Comment by qianjiachun** [comment]
下次遇到会注意一下，感谢建议




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月11日(星期四) 晚上7:36
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"小淳"<189964430@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 建议把直播间的PK也屏蔽了 (#29)





 

 没有触发流程，只要主播开启PK，就会一直匹配对手
 红圈里是在PK开始时的提示，几秒后消失
 蓝圈里是PK过程中一直显示的倒计时，可以手动关闭，当匹到新对手时重复这个过程
