### ISSUE TITLE
可以做一个对标虎牙的不？

### ISSUE THREAD

**Issue by AK47buibuibui** [qianjiachun/douyuEx#30]

**Comment by qianjiachun** [comment]
不能



---原始邮件---
发件人: "依"<notifications@github.com&gt;
发送时间: 2021年2月10日(周三) 凌晨1:22
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [qianjiachun/douyuEx] 可以做一个对标虎牙的不？ (#30)
