### ISSUE TITLE
夜间模式缺陷

### ISSUE THREAD

**Issue by Softland99** [qianjiachun/douyuEx#31]
开启夜间模式后在弹幕框和分区框边缘有白边

**Comment by qianjiachun** [comment]
分区框？有截图嘛看一下

**Comment by Softland99** [comment]
![QQ图片20210217125133](https://user-images.githubusercontent.com/68981891/108157990-efbc8880-711e-11eb-83cd-cae2b498d11a.jpg)

**Comment by qianjiachun** [comment]
我这并没有出现这样的问题。请问是什么浏览器呢？
方便加一下QQ189964430&nbsp; 远程看一下吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月17日(星期三) 中午12:52
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"小淳"<189964430@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 夜间模式缺陷 (#31)

**Comment by Softland99** [comment]
刚刚调了一下缩放比例 应该是我调的缩放90%的原因

**Comment by qianjiachun** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月17日(星期三) 中午12:56
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"小淳"<189964430@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 夜间模式缺陷 (#31)





 
刚刚调了一下缩放比例 应该是我调的缩放90%的原因

**Comment by Softland99** [comment]
如果可以的话还是希望能适配一下不同的缩放比例 这样对DPI比较低的设备还是友好一点

**Comment by qianjiachun** [comment]
已实现适配。下版本更新后就修复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月17日(星期三) 中午1:04
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"小淳"<189964430@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 夜间模式缺陷 (#31)





 
如果可以的话还是希望能适配一下不同的缩放比例 这样对DPI比较低的设备还是友好一点

**Comment by Softland99** [comment]
十分感谢

**Comment by qianjiachun** [comment]
新创了交流QQ群：977387881&nbsp; 可以反馈和通知进度




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月21日(星期天) 下午4:08
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"小淳"<189964430@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 夜间模式缺陷 (#31)





 
十分感谢
