### ISSUE TITLE
Firefox浏览器无法更新脚本

### ISSUE THREAD

**Issue by carnival-in-2000** [qianjiachun/douyuEx#32]
<img width="622" alt="Snipaste_2021-02-21_15-33-35" src="https://user-images.githubusercontent.com/56733420/108618570-3fba8880-745a-11eb-8670-cdb6128a011a.png">

**Comment by qianjiachun** [comment]
https://greasyfork.org/zh-CN/scripts/394497
在这里更新即可。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月21日(星期天) 下午3:34
收件人:&nbsp;"qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianjiachun/douyuEx] Firefox浏览器无法更新脚本 (#32)

**Comment by carnival-in-2000** [comment]
OK谢谢！
