### ISSUE TITLE
希望恢复直播间抽奖

### ISSUE THREAD

**Issue by leapmarmot** [qianjiachun/douyuEx#33]
希望恢复直播间抽奖

**Comment by qianjiachun** [comment]
没有这个功能呀



---原始邮件---
发件人: "Marmot"<notifications@github.com&gt;
发送时间: 2021年2月26日(周五) 晚上10:00
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [qianjiachun/douyuEx] 希望恢复直播间抽奖 (#33)




 
希望恢复直播间抽奖

**Comment by leapmarmot** [comment]
没说清楚。。。是直播间抽奖哪个图标被屏蔽了

**Comment by qianjiachun** [comment]
不可能啊，我没有屏蔽那个东西




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Marmot"<notifications@github.com&gt;; 
发送时间: 2021年2月28日(星期天) 晚上10:07
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com&gt;; 
抄送: "小淳"<189964430@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [qianjiachun/douyuEx] 希望恢复直播间抽奖 (#33)





 
没说清楚。。。是直播间抽奖哪个图标被屏蔽了
