### ISSUE TITLE
进入具体直播间后，关注列表下拉框使用不了鼠标中键

### ISSUE THREAD

**Issue by preacecd** [qianjiachun/douyuEx#35]
在首页时可以使用中键，进入直播间后的可以修改下吗

**Comment by qianjiachun** [comment]
呃。。其实点鼠标左键效果是一样的。关注列表的按键逻辑被我重写成了，左键新标签打开，长按同屏播放。
这个需求很重要的话，我下版本看看能不能加上。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月2日(星期天) 中午11:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 进入具体直播间后，关注列表下拉框使用不了鼠标中键 (#35)





 
在首页时可以使用中键，进入直播间后的可以修改下吗

**Comment by preacecd** [comment]
鼠标左键是直接打开新标签，我习惯中键在后台打开，大佬如果有时间的话麻烦加一下😊

**Comment by preacecd** [comment]
![image](https://user-images.githubusercontent.com/47603911/116809966-a0112900-ab73-11eb-9faa-676bd297c9f9.png)
![image](https://user-images.githubusercontent.com/47603911/116809979-b1f2cc00-ab73-11eb-9809-fcd84dcfa0f8.png)
还有，夜间模式上面会变成空白，算bug么

**Comment by qianjiachun** [comment]
不算。上面的dom背景图变黑了就成这样了。习惯就好 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月2日(星期天) 晚上6:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 进入具体直播间后，关注列表下拉框使用不了鼠标中键 (#35)

**Comment by qianjiachun** [comment]
行我研究下。下版本加------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月2日(星期天) 晚上6:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 进入具体直播间后，关注列表下拉框使用不了鼠标中键 (#35)
