### ISSUE TITLE
和其它脚本冲突：【HTML5视频播放器增强脚本】

### ISSUE THREAD

**Issue by beyond510** [qianjiachun/douyuEx#36]
和其它脚本冲突：【HTML5视频播放器增强脚本】
脚本地址：
https://greasyfork.org/zh-CN/scripts/381682-html5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8%E5%A2%9E%E5%BC%BA%E8%84%9A%E6%9C%AC

具体表现就是，如果这两个脚本同时存在，douyuEx脚本就整体失效了。自动运行的一些功能没有了，页面里的“宠物球”也不会显示。

**Comment by qianjiachun** [comment]
目前没有什么好的办法做到全部兼容。可以不让另一个脚本匹配douyu这个站点




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 凌晨1:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 和其它脚本冲突：【HTML5视频播放器增强脚本】 (#36)





 
和其它脚本冲突：【HTML5视频播放器增强脚本】
 脚本地址：
 https://greasyfork.org/zh-CN/scripts/381682-html5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8%E5%A2%9E%E5%BC%BA%E8%84%9A%E6%9C%AC
 
具体表现就是，如果这两个脚本同时存在，douyuEx脚本就整体失效了。自动运行的一些功能没有了，页面里的“宠物球”也不会显示。

**Comment by beyond510** [comment]
那。。。有好一点的HTML5优化脚本推荐吗？不冲突的

**Comment by qianjiachun** [comment]
暂不了解




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 凌晨1:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 和其它脚本冲突：【HTML5视频播放器增强脚本】 (#36)





 
那。。。有好一点的HTML5优化脚本推荐吗？不冲突的
