### ISSUE TITLE
希望给相机按钮做个开关…

### ISSUE THREAD

**Issue by Itzamana** [qianjiachun/douyuEx#37]
感谢作者，脚本超级好用！
就是直播间的相机按钮如果有个开关就更好了…
另外夜间模式可否适配一下我的关注页面[https://www.douyu.com/directory/myFollow](https://www.douyu.com/directory/myFollow)…

**Comment by qianjiachun** [comment]
相机按钮应该对页面影响已经很小了。
另外不准备做其他页面的适配。。因为做一个页面非常累




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 晚上8:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 希望给相机按钮做个开关… (#37)





 
感谢作者，脚本超级好用！
 就是这个相机按钮如果有个开关就更好了…
 另外夜间模式可否适配一下我的关注页面（https://www.douyu.com/directory/myFollow）…
