### ISSUE TITLE
屏蔽广告功能失效

### ISSUE THREAD

**Issue by sadlulu** [qianjiachun/douyuEx#38]
直播间页面好多广告没法屏蔽，比如
![image](https://user-images.githubusercontent.com/52368635/119174027-eb08b880-ba1c-11eb-9fbe-bd461195b61c.png)
![image](https://user-images.githubusercontent.com/52368635/119174044-f1973000-ba1c-11eb-93db-700ae070ce44.png)
求修复，谢谢

**Comment by qianjiachun** [comment]
这个不是广告。。有些人会需要用的
右侧的可以在弹幕框里点击【拉高】 屏蔽




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月22日(星期六) 凌晨1:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 屏蔽广告功能失效 (#38)





 
直播间页面好多广告没法屏蔽，比如
 
 
 求修复，谢谢

**Comment by sadlulu** [comment]
了解了，感谢大佬及时回复
