### ISSUE TITLE
希望增加一个自动选择最高画质功能

### ISSUE THREAD

**Issue by Tyrone2333** [qianjiachun/douyuEx#40]
每次要手动切换真的好麻烦啊

**Comment by qianjiachun** [comment]
https://greasyfork.org/zh-CN/scripts/396929




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月27日(星期四) 晚上10:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 希望增加一个自动选择最高画质功能 (#40)





 
每次要手动切换真的好麻烦啊
