### ISSUE TITLE
这个可以获取播放了垃圾吗？rtmp

### ISSUE THREAD

**Issue by wei168hua** [qianjiachun/douyuEx#41]
这个可以获取播放了垃圾吗？rtmp

**Comment by qianjiachun** [comment]
目前不支持获取rtmp




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 上午9:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 这个可以获取播放了垃圾吗？rtmp (#41)





 
这个可以获取播放了垃圾吗？rtmp
