### ISSUE TITLE
请问可以指导一下相关代码的作用吗？

### ISSUE THREAD

**Issue by Mishasama** [qianjiachun/douyuEx#42]
主要是想学习一下功能的实现方式，谢谢。

（version      2021.07.05.01）
1. 行 1685 开始，那个API有什么作用？
2. 行 1976 开始，那个API又是做什么的？
3. 行 6193 开始，那个积分系统是哪里的积分？
4. 行 8165 开始，依赖QQ相关的是用来实现什么功能的？

其它有中文内容的部分都能找到斗鱼相关的功能比较好理解，但是这4个貌似没找到具体是用在哪里的，不知道大佬能不能解说一下或者加个注释啥的？谢谢了。

**Comment by qianjiachun** [comment]
1. 获取舔狗文本的接口，你可以GET一下看看，用于舔狗弹幕
2. 获取用户历史弹幕的接口
3. 骆歆直播间的积分系统前端，这个功能可能会在10月份删除
4. 主要是获取斗鱼车队消息，他依赖于qq的接口

**Comment by Mishasama** [comment]
> 1. 获取舔狗文本的接口，你可以GET一下看看，用于舔狗弹幕
> 2. 获取用户历史弹幕的接口
> 3. 骆歆直播间的积分系统前端，这个功能可能会在10月份删除
> 4. 主要是获取斗鱼车队消息，他依赖于qq的接口

哦…原来如此，感谢大佬的回复♥

抱歉还想再请教一下……
那个舔狗文本API是免费开放还是仅限授权的？貌似在[首页](https://chp.shadiao.app/)没发现相关的说明，不知道我能不能直接调用呢？

**Comment by qianjiachun** [comment]
免费的，你直接浏览器访问就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月7日(星期三) 中午1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 请问可以指导一下相关代码的作用吗？ (#42)





   
获取舔狗文本的接口，你可以GET一下看看，用于舔狗弹幕
 
获取用户历史弹幕的接口
 
骆歆直播间的积分系统前端，这个功能可能会在10月份删除
 
主要是获取斗鱼车队消息，他依赖于qq的接口
   
哦…原来如此，感谢大佬的回复♥
 
抱歉还想再请教一下……
 那个舔狗文本API是免费开放还是仅限授权的？貌似在首页没发现相关的说明，不知道我能不能直接调用呢？

**Comment by Mishasama** [comment]
感谢大哥！祝大哥天天火箭不停🚀
