### ISSUE TITLE
更新后

### ISSUE THREAD

**Issue by Fengchen777** [qianjiachun/douyuEx#48]
更新后直播间挂在后台，切换到直播间网页就会刷新，不确定是chrome94的问题还是插件的问题

**Comment by qianjiachun** [comment]
斗鱼本身的后台资源闲置机制。插件在2021年6月16日更新的时候解决了这个问题，然后在2021年7月5日撤销了这个功能，如果你想要使用，可以在源代码里搜索tabswitch相关字眼。
