### ISSUE TITLE
在直播间开启抽奖时无法使用一键领取鱼粮功能

### ISSUE THREAD

**Issue by mrjesen** [qianjiachun/douyuEx#5]
在直播间开启抽奖时无法使用一键领取鱼粮功能

**Comment by qianjiachun** [comment]
你好 是因为抽奖的按钮优先级更高，所以点击后穿透了。可等待抽奖结束后点击

**Comment by mrjesen** [comment]
> 你好 是因为抽奖的按钮优先级更高，所以点击后穿透了。可等待抽奖结束后点击

对呀，所以希望修复一下

**Comment by qianjiachun** [comment]
已修复------------------ 原始邮件 ------------------
发件人: "mrjesen"<notifications@github.com>
发送时间: 2020年4月25日(星期六) 晚上7:47
收件人: "qianjiachun/douyuEx"<douyuEx@noreply.github.com>;
抄送: "qianjiachun"<189964430@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [qianjiachun/douyuEx] 在直播间开启抽奖时无法使用一键领取鱼粮功能 (#5)




  
你好 是因为抽奖的按钮优先级更高，所以点击后穿透了。可等待抽奖结束后点击
  
对呀，所以希望修复一下
 
&mdash;
