### ISSUE TITLE
开了简洁模式就看不了背包了呀

### ISSUE THREAD

**Issue by Jesse1uo** [qianjiachun/douyuEx#51]
背包就被挡住了，有可能解决一下吗，感谢

**Comment by qianjiachun** [comment]
回答过这个问题，可以在“顿顿饭”的提问箱中找一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月27日(周一) 晚上11:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 开了简洁模式就看不了背包了呀 (Issue #51)




 
背包就被挡住了，有可能解决一下吗，感谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
