### ISSUE TITLE
疑似导致时长统计失效

### ISSUE THREAD

**Issue by guansss** [qianjiachun/douyuEx#52]
![2](https://user-images.githubusercontent.com/46285865/147909848-5f839ccf-147a-4ce5-9b38-0a7cba363139.jpg)
![1](https://user-images.githubusercontent.com/46285865/147909836-e3ff23e2-38e4-4ebc-9d14-7aa420c04cb7.jpg)

最近的斗鱼时光机，单个主播的时长统计有很大问题，我估计了一下这28小时应该是我用app看的时间，而网页端观看的时长貌似没有被统计上，所以猜测是脚本影响了时长统计，作者有什么头绪吗

另外有个鱼吧里的[帖子](https://yuba.douyu.com/p/522115651641192898)也有类似的情况

**Comment by qianjiachun** [comment]
是所有使用过脚本的人都出现这样的问题吗？理论上来说脚本没有干预过斗鱼的时长统计



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月3日(周一) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 疑似导致时长统计失效 (Issue #52)




 

 
 
最近的斗鱼时光机，单个主播的时长统计有很大问题，我估计了一下这28小时应该是我用app看的时间，而网页端观看的时长貌似没有被统计上，所以猜测是脚本影响了时长统计，作者有什么头绪吗
 
另外有个鱼吧里的帖子也有类似的情况
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guansss** [comment]
不清楚，目前我见到时长不符的也只有两例而已，所以只是根据我自己的使用情况来推测原因， 姑且先提交一个反馈

**Comment by w6Lc** [comment]
可能是斗鱼只统计手机端的数据

**Comment by guansss** [comment]
不太像，我往年报告里的单个主播也是有几百小时的，应该没理由会突然把网页端排除在外

其实也有可能是浏览器或者账号方面的问题，总之这个也不好证实，就先把 issue 关闭吧
