### ISSUE TITLE
弹幕字体渲染效果较差

### ISSUE THREAD

**Issue by w6Lc** [qianjiachun/douyuEx#53]
![image](https://user-images.githubusercontent.com/49556918/149651106-392c69b1-68a9-4110-87ea-9375b2c007da.png)
字体笔画有的粗有的细，原生的斗鱼弹幕则没有此问题
![image](https://user-images.githubusercontent.com/49556918/149651138-d1ffb404-ac63-4e3b-a624-231b3afd5520.png)

**Comment by qianjiachun** [comment]
是为了让弹幕中的emoji有颜色，就把原生字体改成了细体。如果影响真的比较大我会考虑在下个版本中恢复原生样式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月16日(周日) 下午3:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 弹幕字体渲染效果较差 (Issue #53)




 

 字体笔画有的粗有的细，原生的斗鱼弹幕则没有此问题
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by w6Lc** [comment]
好的，感谢答复
________________________________

**Comment by qianjiachun** [comment]
已经改回斗鱼原生字体
