### ISSUE TITLE
视频页下载按钮允许多次点击

### ISSUE THREAD

**Issue by curoky** [qianjiachun/douyuEx#54]
发现一个小问题，这里的下载按钮只能点击一次，通常情况下问题不大，但是当在A视频播放页点击下载后，又点击当前页的B视频链接时，此时因为是页面内跳转，没有触发浏览器刷新，所以跳到B视频页的时候，下载按钮无法点击。
 
![image](https://user-images.githubusercontent.com/53091022/149663606-8b5dd88b-4759-4ebe-9842-032393efbbbc.png)

这里是不是支持一下允许重复点击就好了。

Thanks 🙏🏻.

**Comment by qianjiachun** [comment]
这个插件不是会提示刷新页面的嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月16日(星期天) 晚上10:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 视频页下载按钮允许多次点击 (Issue #54)





 
发现一个小问题，这里的下载按钮只能点击一次，通常情况下问题不大，但是当在A视频播放页点击下载后，又点击当前页的B视频链接时，此时因为是页面内跳转，没有触发浏览器刷新，所以跳到B视频页的时候，下载按钮无法点击。
 

 
这里是不是支持一下允许重复点击就好了。
 
Thanks 🙏🏻.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by curoky** [comment]
> 这个插件不是会提示刷新页面的嘛

我这边用的是 chrome 97.0.4692.71（正式版本） (x86_64)，第二次点击并没有提示刷新页面，当然即便不提示我也知道要刷新页面。

我这边的场景是要连续下载多个视频（可以理解为合集），现在每次在页面内点击下一集后，还得再手动刷新一下，因为是视频页，所以页面刷新时会特别卡。

所以还是希望能够支持可以重复点击下载按钮，或者跳转到新视频时，可以再次点击下载按钮。🙏🏻

**Comment by qianjiachun** [comment]
我记得我当时就是因为解决不了这个问题所以才要强制刷新的😂。
我研究一下吧，如果能解决的话，将在下版本加上，请留意更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 视频页下载按钮允许多次点击 (Issue #54)





  
这个插件不是会提示刷新页面的嘛
  
我这边用的是 chrome 97.0.4692.71（正式版本） (x86_64)，第二次点击并没有提示刷新页面，当然即便不提示我也知道要刷新页面。
 
我这边的场景是要连续下载多个视频（可以理解为合集），现在每次在页面内点击下一集后，还得再手动刷新一下，因为是视频页，所以页面刷新时会特别卡。
 
所以还是希望能够支持可以重复点击下载按钮，或者跳转到新视频时，可以再次点击下载按钮。🙏🏻
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by curoky** [comment]
嗯嗯，那就太感谢了，最近在下douyu的视频，之前都是f12手动过滤u3m8文件，昨天用上这个插件后，方便太多了，给你点个赞👍🏻

**Comment by qianjiachun** [comment]
很不幸。。实现这个需求好像还有点困难。目前只能刷新
我做了动态获取pointId但是sign算法上出了问题
然后我做了mobile端的尝试但是遇到了跨域问题
so




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 视频页下载按钮允许多次点击 (Issue #54)





 
嗯嗯，那就太感谢了，最近在下douyu的视频，之前都是f12手动过滤u3m8文件，昨天用上这个插件后，方便太多了，给你点个赞👍🏻
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by curoky** [comment]
能不能曲线解决呀，比如当第二次点击下载按钮，直接触发浏览器的刷新操作呢😂

**Comment by qianjiachun** [comment]
可以的，但是这样有点超出用户操作边界变得不可控了
如果你有需要可以搜索关键字【视频内容已改变，请刷新网页后重试】
在上面加一行location.reload()即可


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qianjiachun/douyuEx] 视频页下载按钮允许多次点击 (Issue #54)





 
能不能曲线解决呀，比如当第二次点击下载按钮，直接触发浏览器的刷新操作呢😂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by curoky** [comment]
确实这样做有点过于 trick 了，我自己在油猴里面加就好了，感谢🥳
