### ISSUE TITLE
下载弹幕ass功能在哪

### ISSUE THREAD

**Issue by damao33** [qianjiachun/douyuEx#56]
没有找到..

**Comment by qianjiachun** [comment]
斗鱼视频页面有个下载按钮




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 晚上9:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 下载弹幕ass功能在哪 (Issue #56)





 
没有找到..

**Comment by damao33** [comment]
对正在直播的直播间可以在potplayer里看到弹幕吗，我是用potplayer直接看直播源

**Comment by qianjiachun** [comment]
不能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 晚上9:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qianjiachun/douyuEx] 下载弹幕ass功能在哪 (Issue #56)




 
对正在直播的直播间可以在potplayer里看到弹幕吗，我是用potplayer直接看直播源

**Comment by damao33** [comment]
> 

谢谢回复
