### ISSUE TITLE
关键词禁言不会用啊

### ISSUE THREAD

**Issue by Heporis** [qianjiachun/douyuEx#57]
怎么写能具体讲解一下嘛？给个例子吧。导出的内容也没有具体的格式，无从下手

**Comment by Heporis** [comment]
> 看图里 有步骤 ![image](https://user-images.githubusercontent.com/43806319/162649554-bc04cfb5-22be-42cb-8a62-ac4f30fc975f.png)

这个词条还能点啊。。。。我说怎么没有你这个面板呢。。。🤣

**Comment by qianjiachun** [comment]
操作步骤




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qianjiachun/douyuEx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 晚上11:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 关键词禁言不会用啊 (Issue #57)





 
怎么写能具体讲解一下嘛？给个例子吧
