### ISSUE TITLE
以后会做虎牙的吗

### ISSUE THREAD

**Issue by Leonsama** [qianjiachun/douyuEx#58]

**Comment by qianjiachun** [comment]
如果斗鱼倒闭了，或者我换了别的直播平台看了，会做

**Comment by IkaMusumeGitHub** [comment]
> 如果斗鱼倒闭了，或者我换了别的直播平台看了，会做

感谢分享

**Comment by qianjiachun** [comment]
https://github.com/wbt5/real-url/



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月16日(星期一) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qianjiachun/douyuEx] 以后会做虎牙的吗 (Issue #58)





  
如果斗鱼倒闭了，或者我换了别的直播平台看了，会做
  
大佬借楼请教一下 真实直播流的cdn是怎么抓到的

**Comment by redstone1994** [comment]
> https://github.com/wbt5/real-url/
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年5月16日(星期一) 晚上9:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [qianjiachun/douyuEx] 以后会做虎牙的吗 (Issue #58) 如果斗鱼倒闭了，或者我换了别的直播平台看了，会做 大佬借楼请教一下 真实直播流的cdn是怎么抓到的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我看到这个库了，但是这个的地址已经过期了

**Comment by redstone1994** [comment]
> 

感谢回复，我再看看
