### ISSUE TITLE
使用最新版4.16油猴提示让我升级油猴，两台电脑都是这样

### ISSUE THREAD

**Issue by syj819** [qianjiachun/douyuEx#59]
![Uploading image.png…]()

**Comment by qianjiachun** [comment]
换最新版chrome浏览器 再装最新tampermonkey试试？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月8日(周日) 凌晨1:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 使用最新版4.16油猴提示让我升级油猴，两台电脑都是这样 (Issue #59)

**Comment by john5du** [comment]
同样的问题
![image](https://user-images.githubusercontent.com/45614150/204960200-1a4644de-7b55-46bb-b5b6-314ea40a1c04.png)
![image](https://user-images.githubusercontent.com/45614150/204960151-e1ea12a3-41c0-4b25-8608-cbd93e5c7a8d.png)
![image](https://user-images.githubusercontent.com/45614150/204960343-bd863a61-00d1-4f5c-9397-822fdccf9716.png)

**Comment by qianjiachun** [comment]
可能页面上提示的不太准确。其实是因为找不到tampermonkey中的方法才提示这个。
我这的tampermonkey版本是4.16.1。没有发现问题

**Comment by tjx666** [comment]
@qianjiachun 和 @john5du 一样的问题。我啥都是最新版

**Comment by tjx666** [comment]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/41773861/217009134-7584e150-5e76-49c8-a333-0b2744f8aafc.png">

<img width="396" alt="image" src="https://user-images.githubusercontent.com/41773861/217009183-c09e42dc-0ce0-46b7-ad6b-cab3703ecdd2.png">

<img width="693" alt="image" src="https://user-images.githubusercontent.com/41773861/217009235-7b18df61-e9da-4eea-8271-11c59514399d.png">

**Comment by qianjiachun** [comment]
其实并不是版本太低，而是该功能依赖的函数缺失。换个版本试试？换个浏览器试试？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月6日(周一) 晚上11:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qianjiachun/douyuEx] 使用最新版4.16油猴提示让我升级油猴，两台电脑都是这样 (Issue #59)

**Comment by syj819** [comment]
一直都没看到这些回复，我之后使用了测试版的油猴就可以使用了。
另外这个只是多账号的提示，其他功能都是正常使用的。
我现在同时使用两个油猴，正常版的正常使用，测试版专门安装了这个斗鱼插件，看到这个回复的人可以参考一下。

**Comment by tjx666** [comment]
我换成油猴 beta 版就可以了

**Comment by qianjiachun** [comment]
> @qianjiachun 是使用了啥 beta 版油猴才有的 api？我觉得这个问题不算解决吧，我还好知道怎样把稳定版的插件导出，在 beta 版恢复，别的用户就不清楚了...

我做这个功能的时候，使用的版本是正式版。但是后续tampermonkey的更新经常会有break changes。所以目前这个问题我觉得还是换版本解决吧，因为我也没法控制，这个功能必须依赖这个api。。

我在这贴一下我目前的tampermonkey版本：v4.18.1 正式版（edge应用商店安装）
