### ISSUE TITLE
有没有一键所有一键的功能，还有鱼吧视频点击加载后会刷新网页无法观看。

### ISSUE THREAD

**Issue by lycaptain** [qianjiachun/douyuEx#6]
斗鱼鱼吧视频点击会刷新网页用的是新版edge浏览器才会出现。禁用后就没问题，只要运行脚本就会复现。

**Comment by qianjiachun** [comment]
你好，脚本没有匹配过yuba.douyu.com这个域名，所以理论上不会导致你所说的bug。并且亲测没有出现你的问题，本人浏览器为搜狗和chrome

**Comment by lycaptain** [comment]
> 你好，脚本没有匹配过yuba.douyu.com这个域名，所以理论上不会导致你所说的bug。并且亲测没有出现你的问题，本人浏览器为搜狗和chrome

我也只是在新版edge浏览器才有这个问题，在是否允许运行flash的弹窗点击后就会刷新页面。

**Comment by qianjiachun** [comment]
呃。。那我暂时无能为力了:(
