### ISSUE TITLE
System showed Trojan:Win32/Wacatac.H!ml detected

### ISSUE THREAD

**Issue by traveleryyk1999** [qianjiachun/douyuEx#61]
After I git clone this project and tried to open the "Tampermonkey编译器.exe", the Windows defender showed the Trojan:Win32/Wacatac.H!ml, which is a virus had been detected and deleted it automatically.

System: Windows 10, Version 1909

**Comment by qianjiachun** [comment]
😂Oh, sorry, let me explain this file: this file is developed and compiled by a Chinese programming language "易语言". This language has often been used to write game plug-ins or viruses, resulting in many antivirus software engines directly thinking that the software written in this language is a virus.



Of course, please rest assured that there is no virus in this software. I also give the corresponding source code in the directory, "Tampermonkey编译器.e".



This is a misunderstanding😥



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 4, 2022 08:44 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [qianjiachun/douyuEx] System showed Trojan:Win32/Wacatac.H!mldetected (Issue #61)




 
After I git clone this project and tried to open the "Tampermonkey编译器.exe", the Windows defender showed the Trojan:Win32/Wacatac.H!ml, which is a virus had been detected and deleted it automatically.
 
System: Windows 10, Version 1909

**Comment by traveleryyk1999** [comment]
Thank you for your clarification!
