### ISSUE TITLE
音频流直链

### ISSUE THREAD

**Issue by jellycooker** [qianjiachun/douyuEx#62]
插件很好用，谢谢
能复制音频流直链吗? 想在本地播放，和视频流一样。
https://github.com/qianjiachun/douyuEx/blob/master/src/require/RealLive/Douyu/RealLive_Douyu.js#L7
https://github.com/qianjiachun/douyuEx/blob/master/src/packages/PopupPlayer/PopupPlayer.js#L308
https://github.com/qianjiachun/douyuEx/blob/master/src/packages/PopupPlayer/PopupPlayer.js#L325

**Comment by qianjiachun** [comment]
已经有了，点击切换音频流直播后，点击弹出的小窗左上角的白色标题即可。

**Comment by jellycooker** [comment]
> 已经有了，点击切换音频流直播后，点击弹出的小窗左上角的白色标题即可。

这样复制出来的还是flv视频流，你用h5播放器确实可以不解码画面。但我想用potplayer直接放音频。
douyu客户端有音频流线路，可惜我不会抓包

**Comment by qianjiachun** [comment]
噢是我疏漏了。。。不过我也懒得改了😂😂
你在复制出来的直播流地址后面加上 &only-audio=1
就可以实现音频流了

**Comment by jellycooker** [comment]
> 噢是我疏漏了。。。不过我也懒得改了😂😂 你在复制出来的直播流地址后面加上 &only-audio=1 就可以实现音频流了
可以了，非常感谢!!
