### ISSUE TITLE
特殊时期显示弹幕功能如何启用？

### ISSUE THREAD

**Issue by TheWastedYears** [qianjiachun/douyuEx#63]
RT  没找到功能入口

**Comment by qianjiachun** [comment]
不需要启用。自动生效



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月4日(周日) 凌晨1:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 特殊时期显示弹幕功能如何启用？ (Issue #63)
