### ISSUE TITLE
精简部分无效

### ISSUE THREAD

**Issue by wk4work** [qianjiachun/douyuEx#66]
下方礼物栏，右上角嘉宾栏没有删除
adblock拦截对应元素是

- douyu.com##.ToolbarActivityArea
- douyu.com##.ToolbarGiftArea
- douyu.com##.ChatRank-rankWraper.is-enter
- douyu.com##.ChatRank
- douyu.com##.layout-Player-rank

**Comment by qianjiachun** [comment]
贵宾栏是故意留的。如果你想隐藏，可以鼠标放到弹幕区，然后在清屏/锁屏旁边点击 拉伸即可隐藏贵宾栏



---原始邮件---
发件人: "Hatsune ***@***.***&gt;
发送时间: 2022年12月13日(周二) 晚上11:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 精简部分无效 (Issue #66)




 
下发礼物栏，右上角嘉宾栏没有删除
 adblock拦截对应元素是
  
douyu.com##.ToolbarActivityArea
 
douyu.com##.ToolbarGiftArea
 
douyu.com##.ChatRank-rankWraper.is-enter
 
douyu.com##.ChatRank
 
douyu.com##.layout-Player-rank
