### ISSUE TITLE
进入直播间不提示双倍亲密度，请修复一下

### ISSUE THREAD

**Issue by beoo-i** [qianjiachun/douyuEx#68]
[![pSt4nfI.png](https://s1.ax1x.com/2023/01/25/pSt4nfI.png)](https://imgse.com/i/pSt4nfI)

**Comment by qianjiachun** [comment]
这个好像被我当成广告（悬浮元素）屏蔽掉了。我个人觉得收益>损失。所以暂时不准备改掉
