### ISSUE TITLE
有的时候会报错但是多刷几次或者多重启几次浏览器就好了

### ISSUE THREAD

**Issue by CoderChang65535** [qianjiachun/douyuEx#71]
音效增强插件也报错

**Comment by CoderChang65535** [comment]
场景是我用chrome多屏幕开了两个窗口，启用了chrome的启动时打开上次关闭页面
启动的时候会自动打开全部两个窗口，然后插件就会报错，只能分别关闭窗口让单窗口启动的时候才能工作

**Comment by qianjiachun** [comment]
报错信息方便贴一下吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月2日(周四) 晚上6:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [qianjiachun/douyuEx] 有的时候会报错但是多刷几次或者多重启几次浏览器就好了 (Issue #71)




 
场景是我用chrome多屏幕开了两个窗口，启用了chrome的启动时打开上次关闭页面
 启动的时候会自动打开全部两个窗口，然后插件就会报错，只能分别关闭窗口让单窗口启动的时候才能工作

**Comment by CoderChang65535** [comment]
![image](https://user-images.githubusercontent.com/19420270/222897713-c8d8bee4-bbd7-43c1-b5ce-2a1d8ba93a6d.png)

Uncaught (in promise) Error: Browser is not supported by ExtendedCss.
    at new ExtendedCss (content-script-start.js:5403)
    at applyExtendedCss (content-script-start.js:7744)
    at applySelectors (content-script-start.js:7762)
    at processCssAndScriptsResponse (content-script-start.js:7876)
    at tryLoadCssAndScripts (content-script-start.js:7894)

DevTools 无法加载来源映射：无法加载 chrome-extension://jinjaccalgkegednnccohejagnlnfdag/gif.js.map 的内容：HTTP 错误：状态代码 404，net::ERR_UNKNOWN_URL_SCHEME

Uncaught (in promise) DOMException: Blocked a restricted frame with origin "https://www.douyu.com" from accessing another frame.
    at getOwnPropertyDescriptor (<anonymous>)

**Comment by qianjiachun** [comment]
方便加一下QQ 189964430 我远程看一下吗
