### ISSUE TITLE
提个小小的建议

### ISSUE THREAD

**Issue by StupidPz** [qianjiachun/douyuEx#72]
能否在复制直播流的按钮旁添加一个用potplayer或者vlc打开,毕竟复制直播流的话都是要用第三方播放器播放的把

**Comment by qianjiachun** [comment]
这个功能之前有说过，总而言之就是暂不考虑哈，谢谢建议



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月1日(周六) 凌晨4:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 提个小小的建议 (Issue #72)




 
能否在复制直播流的按钮旁添加一个用potplayer或者vlc打开,毕竟复制直播流的话都是要用第三方播放器播放的把
