### ISSUE TITLE
是否可以新增一键网页全屏/宝箱收获统计的功能？

### ISSUE THREAD

**Issue by wsyzzz** [qianjiachun/douyuEx#73]
谢谢大佬的插件，在使用过程中发现有这么几个仍然觉得可以改进的地方。
1、播放界面优化一键网页全屏功能或默认网页全屏：我使用edge观看网页全屏的时候，双击画面进入斗鱼的网页全屏模式之后，右边的弹幕聊天框仍然需要再点击一下边界，才能把右侧的聊天框关掉，是否可以新增默认网页“真”全屏？
2、自动抢礼物红包/自动抢宝箱功能开启之后，貌似需要一个统计来表明该功能辅助抢到了多少道具。

**Comment by qianjiachun** [comment]
谢谢反馈

1. 这个功能我个人觉得个性化太强，适合单独再做一个脚本来实现。douyuex的理念是开箱即用，无侵入式，并不会对斗鱼原生网页的功能做主线上的干预。
2. emmm，说实话这个功能我好久好久没有维护了，我甚至不知道这个现在还有没有用（个人太忙了没有时间弄😭）

有条件的话还是希望大家能参与到开源中来
