### ISSUE TITLE
大佬，有木有斗鱼PC段多开的工具啊

### ISSUE THREAD

**Issue by shemengjia** [qianjiachun/douyuEx#74]

**Comment by qianjiachun** [comment]
live.douyuex.com



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月16日(周五) 晚上9:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 大佬，有木有斗鱼PC段多开的工具啊 (Issue #74)
