### ISSUE TITLE
一键续牌功能失效

### ISSUE THREAD

**Issue by ARonDellon** [qianjiachun/douyuEx#75]
背包里有荧光棒，点击无反应

**Comment by qianjiachun** [comment]
测试了一下 没有问题，不过我的是钻粉荧光棒。
你可以试试输出一下你背包里的礼物id给我看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月20日(周二) 晚上11:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 一键续牌功能失效 (Issue #75)




 
背包里有荧光棒，点击无反应

**Comment by ARonDellon** [comment]
https://github.com/qianjiachun/douyuEx/assets/9428073/e769a73d-afc7-490d-a314-1de2c0e6f980
![微信截图_20230708120017](https://github.com/qianjiachun/douyuEx/assets/9428073/d80dcbc7-c38b-4f88-8d3d-9744b5596371)
没有清空背包的按钮，一键续牌点击也没生效

**Comment by ARonDellon** [comment]
视频预览黑屏，下载下来可以看

**Comment by qianjiachun** [comment]
我这里测试没有问题。
要不尝试一下重装一下tampermonkey（换个版本）？

实在不行你加我QQ189964430，我详细看一下

**Comment by ARonDellon** [comment]
好我重装试试

**Comment by qianjiachun** [comment]
长时间无后续 视为解决
