### ISSUE TITLE
新版本自动屏蔽了右侧的活跃度和贵宾数吗？有没设置能恢复显示？

### ISSUE THREAD

**Issue by Dradows** [qianjiachun/douyuEx#77]

**Comment by qianjiachun** [comment]
没有啊？截个图看看呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月24日(周一) 凌晨0:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 新版本自动屏蔽了右侧的活跃度和贵宾数吗？有没设置能恢复显示？ (Issue #77)

**Comment by Dradows** [comment]
↓没开插件的
![QQ截图20230724010339](https://github.com/qianjiachun/douyuEx/assets/32986753/d140e4bc-9886-4603-ab73-cfcbd6a15b58)

↓开了插件的
![QQ截图20230724010403](https://github.com/qianjiachun/douyuEx/assets/32986753/5da64190-5194-467c-8e68-cf56b668f58e)

以前是正常显示的，大概两三周前的某次更新后就没了

**Comment by qianjiachun** [comment]
是你自己点了【拉高】
鼠标移到弹幕区域，在清屏锁屏按钮旁有拉高选项



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月24日(周一) 凌晨1:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qianjiachun/douyuEx] 新版本自动屏蔽了右侧的活跃度和贵宾数吗？有没设置能恢复显示？ (Issue #77)




 
↓没开插件的
 
 
↓开了插件的
 
 
以前是正常显示的，大概两三周前的某次更新后就没了
