### ISSUE TITLE
这个骆歆插件为什么不能自动更新啊

### ISSUE THREAD

**Issue by wei168hua** [qianjiachun/douyuEx#8]
这个插件为什么不能更新

**Comment by qianjiachun** [comment]
自动提醒更新。你得手动更新------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;wei168hua&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月10日(星期三) 中午12:00
收件人:&nbsp;&quot;qianjiachun/douyuEx&quot;<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 这个骆歆插件为什么不能自动更新啊 (#8)
