### ISSUE TITLE
斗鱼高能弹幕SC屏蔽

### ISSUE THREAD

**Issue by suAmanmo** [qianjiachun/douyuEx#80]
SC的声音播报可以被屏蔽吗

**Comment by qianjiachun** [comment]
没有研究过 有空我看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月23日(周三) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 斗鱼高能弹幕SC屏蔽 (Issue #80)




 
SC的声音播报可以被屏蔽吗

**Comment by qianjiachun** [comment]
SC是入流的，目前无法靠插件屏蔽
