### ISSUE TITLE
点击安装按钮无法自动安装

### ISSUE THREAD

**Issue by ACaiGarden** [qianjiachun/douyuEx#81]
进入：https://xiaochunchun.gitee.io/douyuex/install/web.html
点击：“安装2023.08.31.02版本”按钮
跳转到URL：http://src.douyuex.com/src/douyuex.user.js
空白页，没有进行安装

油猴版本v4.19.0

**Comment by qianjiachun** [comment]
你看看脚本安装成功没（看有没有精灵球）
或者试试在gf上安装
https://greasyfork.org/zh-CN/scripts/394497

**Comment by ACaiGarden** [comment]
已经通过其他方式安装上啦～谢谢小淳👍🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月13日(周三) 晚上11:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qianjiachun/douyuEx] 点击安装按钮无法自动安装 (Issue #81)




 
你看看脚本安装成功没（看有没有精灵球）
 或者试试在gf上安装
 https://greasyfork.org/zh-CN/scripts/394497
