### ISSUE TITLE
直播间挂机检测功能

### ISSUE THREAD

**Issue by mcslll** [qianjiachun/douyuEx#82]
我是之前在油猴评论区留言能否加入挂机检测的那位，这个功能其实是我在使用bilibili-旧播放页这个插件时看到的（[代码地址](https://github.com/MotooriKashin/Bilibili-Old)），加上斗鱼也有这个问题，我就提了。本人有程序相关的知识，但没接触过js，接下来的话如有冒犯请见谅。
我先是试着ctrl+f搜索bilibili-旧播放页这个插件的源码，找到了对应挂机代码的实现，询问了chatgpt。我把相关的代码位置和chatgpt的回答截图了，不知道有无参考价值，如果能够添加上这个功能，那真是万分感谢了
![屏幕截图 2023-10-11 223631](https://github.com/qianjiachun/douyuEx/assets/114303595/c679c9eb-d767-457a-922c-dea469e5e2a5)
![屏幕截图 2023-10-11 224655](https://github.com/qianjiachun/douyuEx/assets/114303595/aae52222-223d-4aac-b0f1-c54def00e3fd)

**Comment by qianjiachun** [comment]
感谢建议👍，我看了一下代码，原理是通过覆写原生计时器的方法来禁止挂机检测
实际上这是应用层的行为，也就是说也许B站是这么实现检测的，但是斗鱼不是这么实现的。

douyuex之前其实做过斗鱼的防挂机检测（禁止标签冻结），但是因为体验不够好就删掉了（你可以在douyuex的代码中搜索`initPkg_TabSwitch`找到相关代码并开启）
加之这个挂机检测其实是用于节省资源的
综上考虑我就没有再恢复这个功能

**Comment by qianjiachun** [comment]
2023.10.17.01版本已增加该功能
![image](https://github.com/qianjiachun/douyuEx/assets/43806319/64387dc4-eb74-4c19-91eb-6f8de6be9bae)

**Comment by mcslll** [comment]
> 2023.10.17.01版本已增加该功能 ![image](https://user-images.githubusercontent.com/43806319/275700440-64387dc4-eb74-4c19-91eb-6f8de6be9bae.png)

十分感谢
