### ISSUE TITLE
斗鱼直播用竖屏播放直播，全屏状态下旋转画面到90度或者270度画面竖过来的时候，不会自动缩放到填满屏幕，反而还缩小了

### ISSUE THREAD

**Issue by RorschachOo** [qianjiachun/douyuEx#83]
不知道为什么，旋转的缩放不会自适应窗口的大小。作者可以试一下竖屏状态下旋转视频画面就知道了。

**Comment by qianjiachun** [comment]
你是说显示器（pc）竖屏？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月21日(周日) 中午11:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 斗鱼直播用竖屏播放直播，全屏状态下旋转画面到90度或者270度画面竖过来的时候，不会自动缩放到填满屏幕，反而还缩小了 (Issue #83)




 
不知道为什么，旋转的缩放不会自适应窗口的大小。作者可以试一下竖屏状态下旋转视频画面就知道了。

**Comment by RorschachOo** [comment]
是的。

**Comment by qianjiachun** [comment]
我还真没试过显示器竖过来的情况😂
以后有机会看看吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月21日(周日) 中午12:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qianjiachun/douyuEx] 斗鱼直播用竖屏播放直播，全屏状态下旋转画面到90度或者270度画面竖过来的时候，不会自动缩放到填满屏幕，反而还缩小了 (Issue #83)




 
是的。

**Comment by RorschachOo** [comment]
应该是10395、10396行的缩放代码有问题，我暂时把缩放宽高比掉换了一下：transformCss.scale = "scale(" + String(liveVideoNode.videoWidth / liveVideoNode.videoHeight) + ")"，全屏状态下可以铺满屏幕，但是窗口化还是不能适应窗口，我先这么凑活用。应该改成旋转的时候适应窗口的比例，是最好。

**Comment by qianjiachun** [comment]
感谢指出。后面有空了看下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月21日(周日) 中午1:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qianjiachun/douyuEx] 斗鱼直播用竖屏播放直播，全屏状态下旋转画面到90度或者270度画面竖过来的时候，不会自动缩放到填满屏幕，反而还缩小了 (Issue #83)




 
应该是10395、10396行的缩放代码有问题，我暂时把缩放宽高比掉换了一下：transformCss.scale = "scale(" + String(liveVideoNode.videoWidth / liveVideoNode.videoHeight) + ")"，全屏状态下可以铺满屏幕，但是窗口化还是不能适应窗口，我先这么凑活用。应该改成旋转的时候适应窗口的比例，是最好。

**Comment by qianjiachun** [comment]
2024.01.29.01版本已经修复

**Comment by RorschachOo** [comment]
真的修复了，非常感谢作者。
