### ISSUE TITLE
可否增加进入直播间后的自动网页全屏功能？

### ISSUE THREAD

**Issue by PaTTeeL** [qianjiachun/douyuEx#84]
现在因为有各种主题活动还有代言商务之类的，进入每个直播间后，直播窗口的大小位置都不一样，每次都要折腾一下甚至好几下才能正常看直播，能否在页面防挂机选项的右边增加一个默认网页全屏的功能，进入直播页面后自动网页全屏模式，省心也省事多了。

门外汉发现只要在网页开发者模式下向body的class里面加入"is-fullScreenPage"就会自动跳转，但试过用adguard和ublock origin都搞不定这个动作，如果能实现的话感激不尽！

![image](https://github.com/qianjiachun/douyuEx/assets/9150277/0526026a-d0b8-452f-84af-7c06e9389870)

**Comment by qianjiachun** [comment]
https://greasyfork.org/zh-CN/scripts/396929



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月2日(周五) 凌晨1:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] 可否增加进入直播间后的自动网页全屏功能？ (Issue #84)




 
现在因为有各种主题活动还有代言商务之类的，进入每个直播间后，直播窗口的大小位置都不一样，每次都要折腾一下甚至好几下才能正常看直播，能否在页面防挂机选项的右边增加一个默认网页全屏的功能，进入直播页面后自动网页全屏模式，省心也省事多了。
 
门外汉发现只要在网页开发者模式下向body的class里面加入"is-fullScreenPage"就会自动跳转，但试过用adguard和ublock origin都搞不定这个动作，如果能实现的话感激不尽！
 
image.png (view on web)

**Comment by PaTTeeL** [comment]
感谢！已经装好了，我在greasyfork.org搜过斗鱼网页全屏，当时没见到这插件。

另外能不能整合进douyuex，这也算两个直播间增强功能？

还有网页全屏和最高画质是否能做成可选项？比如移动办公使用流量卡的时候就只希望网页全屏，画质不一定要最高。

> https://greasyfork.org/zh-CN/scripts/396929
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月2日(周五) 凌晨1:41 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qianjiachun/douyuEx] 可否增加进入直播间后的自动网页全屏功能？ (Issue #84) 现在因为有各种主题活动还有代言商务之类的，进入每个直播间后，直播窗口的大小位置都不一样，每次都要折腾一下甚至好几下才能正常看直播，能否在页面防挂机选项的右边增加一个默认网页全屏的功能，进入直播页面后自动网页全屏模式，省心也省事多了。 门外汉发现只要在网页开发者模式下向body的class里面加入"is-fullScreenPage"就会自动跳转，但试过用adguard和ublock origin都搞不定这个动作，如果能实现的话感激不尽！ image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by qianjiachun** [comment]
当时分成两个脚本写是因为保持douyuex本体开箱即用的特性。
因为有的用户他不想一进来就全屏，做成开关的话又多一个设置（不太喜欢太多设置）

**Comment by PaTTeeL** [comment]
嗯嗯，理解的，不过现在已经有阻止p2p和页面防挂机的了，可不可以再加上网页全屏和最高画质凑个整呢？

> 当时分成两个脚本写是因为保持douyuex本体开箱即用的特性。 因为有的用户他不想一进来就全屏，做成开关的话又多一个设置（不太喜欢太多设置）

**Comment by qianjiachun** [comment]
下版本看情况弄吧

**Comment by qianjiachun** [comment]
2024.02.02.01版本已加入该功能
