### ISSUE TITLE
收到的弹幕被认为发送失败

### ISSUE THREAD

**Issue by SeasClouds** [qianjiachun/douyuEx#86]
![image](https://github.com/qianjiachun/douyuEx/assets/44010231/9f501620-e57c-466f-8007-a876ae12824d)
似乎收到所有的vip弹幕都是错的

**Comment by qianjiachun** [comment]
紧急推了个新版本2024.03.25.03，暂时性去掉校验飘屏弹幕
有较大误差，以后看情况再加。

更新到新版本即可
