### ISSUE TITLE
功能栏关闭建议

### ISSUE THREAD

**Issue by 9WiSHao** [qianjiachun/douyuEx#87]
现在是点击精灵球打开功能栏，再点击关闭功能栏
考虑到功能栏底部的东西或许会有人使用，关闭功能栏应该是个更符合直觉的操作。现在的再次点击关闭其实有点不符合直觉，我好长时间之后才知道再次点击是关闭
是否考虑单独在打开的功能栏里加一个x号点击关闭，
或者是检测功能栏的鼠标悬浮事件，一定时间鼠标不在上面自动关闭，鼠标经过则重置关闭倒计时的定时器

**Comment by qianjiachun** [comment]
😂其实当时是为了偷懒没弄这些。。
这个功能后面有空加上，近期没时间emmm，也欢迎提交PR

**Comment by qianjiachun** [comment]
#88
