### ISSUE TITLE
为啥抢宝箱这些功能需要骆歆牌子？？？

### ISSUE THREAD

**Issue by hjf6441** [qianjiachun/douyuEx#9]
为啥抢宝箱这些功能需要骆歆牌子？？？

**Comment by qianjiachun** [comment]
没有为什么------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;hjf6441&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月16日(星期二) 中午12:15
收件人:&nbsp;&quot;qianjiachun/douyuEx&quot;<douyuEx@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[qianjiachun/douyuEx] 为啥抢宝箱这些功能需要骆歆牌子？？？ (#9)

**Comment by hjf6441** [comment]
我的意思是 你可以加一个赞赏功能

**Comment by qianjiachun** [comment]
目前脚本不以任何形式盈利。

**Comment by ocean0117** [comment]
发明插件的人喜欢骆歆呗~总不能是骆歆开发的吧哈哈

**Comment by AmyRose1288** [comment]
> 发明插件的人喜欢骆歆呗~总不能是骆歆开发的吧哈哈

听说还真是他开发的，然后第三方负责发布



> 目前脚本不以任何形式盈利。

不盈利？？6级牌子你知道是多少人民币嘛？
