### ISSUE TITLE
[Bug report] 防止自动暂停功能失效

### ISSUE THREAD

**Issue by xArbiterx** [qianjiachun/douyuEx#92]
description:
失效很久了，几个版本都没有解决，我挂着直播玩手机/刷网页经常就停了

how to reproduce:
开个直播挂机直到暂停

**Comment by qianjiachun** [comment]
该功能已经改为独立开关，叫做：防页面挂机


在功能条红色那个图标里面有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月11日(周日) 晚上7:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qianjiachun/douyuEx] [Bug report] 防止自动暂停功能失效 (Issue #92)




 
description:
 失效很久了，几个版本都没有解决，我挂着直播玩手机/刷网页经常就停了
 
how to reproduce:
 开个直播挂机直到暂停

**Comment by xArbiterx** [comment]
> 该功能已经改为独立开关，叫做：防页面挂机 在功能条红色那个图标里面有

在扩展功能里打开了，很久之前打开这个开关是有效的，后来我取消再点也没有用。

**Comment by qianjiachun** [comment]
那可能斗鱼改了这个功能了？不太清楚
