### ISSUE TITLE
【求助】复制直播流问题

### ISSUE THREAD

**Issue by ailx1101** [qianjiachun/douyuEx#96]
复制直播流到Potplayer中播放会很卡顿，速度在600KB/s左右，网络问题问题，其他的视频源可以正常播放，唯独斗鱼直播源会很卡顿。不知道是斗鱼限制还是什么情况，请求作者大大抽时间查看一下是否存在这个问题。
测试直播间：96291
主播：东北大鹌鹑
如果没有问题的话，请关闭此issues。谢谢

**Comment by qianjiachun** [comment]
是potplayer的问题，你可以试试放到[VLC](https://www.videolan.org/vlc/index.zh_CN.html)里播放一下试试

**Comment by Zxilly** [comment]
可以用streamlink中继一下，好很多
